name: test
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Test
      run: make test
